### ISSUE TITLE
Inject Custom ILogger

### ISSUE THREAD

**Issue by bense4ger** [holgerleichsenring/AutofacOnFunctions#9]
I've created a custom implementation of an ILogger but I can't seem to get it injected into my function.  I'm reasonably familiar with AutoFac but I can't quite follow how everything is wired up in this instance.

Please could you provide a really quick guide as to how to use a custom logger?

Edit - For clarity, I'm using .Net Framework rather than Standard

**Comment by holgerleichsenring** [comment]
Hi bense4ger,

for adding own custom logger there are actually two possibilities as far as I know:
- adding the logging within your function, which means logging must be initialized in function itself. I consider that to be pretty ugly, which is the reason why I added injectable logging
- I believe the loggingmanager can be used to provide custom logging. Unluckily currently I do not know how to do this. 

For what reason do you need to do it? It is probably more easy to connect your azure functions directly to Application Insights which is just a mouse click in azure portal.

Please let me know your thoughts

**Comment by holgerleichsenring** [comment]
close issue due to inactivity
